version: "3.9"
 
networks:
  my-network:
 
volumes:
  ollama_data:
  qdrant_data:
  elastic_data:
  hf_cache:
  rm_uploads:
  rm_logs:
  ebrd_uploads:
  postgres-data:
  redis-data:
  mssql-data:
  aiagent-frontend-data:
  aiagent-backend-data:
  aiagent-agent-data:
  aiagent-workflow-data:
 
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - my-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - my-network
  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "7233:7233"
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network
  aiagent-frontend:
    image: rithikbhan/aiagent-frontend:v1
    container_name: aiagent-frontend
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - aiagent-frontend-data:/app/data
  aiagent-backend:
    image: rithikbhan/aiagent-backend:v1
    container_name: aiagent-backend
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - aiagent-backend-data:/app/data
  aiagent-agent:
    image: rithikbhan/aiagent-agent:v1
    container_name: aiagent-agent
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - aiagent-agent-data:/app/data
  aiagent-workflow:
    image: rithikbhan/aiagent-workflow:v1
    container_name: aiagent-workflow
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - aiagent-workflow-data:/app/data

  rm-agent:
    image: anuj2806/rm-agent:sha-7ebd935
    container_name: rm-agent
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - rm_uploads:/app/uploads
      - rm_logs:/app/logs
  ebrd_clos:
    image: anuj2806/ebrd_clos:sha-3b4924b
    container_name: ebrd_clos
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - ebrd_uploads:/app/uploads
  donut_rhb:
    image: ankitshubham/donut_rhb:latest
    container_name: donut_rhb
    networks:
      - my-network
    env_file:
      - .env
  traderfp:
    image: anuj2806/traderfp:sha-2eca94d
    container_name: traderfp
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - hf_cache:/app/models
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - ollama_data:/root/.ollama
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - qdrant_data:/qdrant/storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.3
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - my-network
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - ollama
      - qdrant
      - elasticsearch
    ports:
      - "443:443"
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl