events {}
 
http {
  server {
    listen 443 ssl;
 
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/newgensoftware.key;
 
    location / {
      return 200 "Welcome to AI NSG. Server is running. For more information contact anujsingh@newgensoft.com.";
    }
 
    location /ollama/ {
      proxy_pass http://ollama:11434/;
    }
    location /qdrant/ {
         proxy_pass http://qdrant:6333/;
    }
    location /traderfp/ {
	    proxy_pass http://traderfp:8000/;
      proxy_connect_timeout 300;
      proxy_send_timeout 300;
      proxy_read_timeout 300;
    }
    location /ebrd_clos/ {
	    proxy_pass http://ebrd_clos:8000/;
      proxy_connect_timeout 300;
      proxy_send_timeout 300;
      proxy_read_timeout 300;
      client_max_body_size 100M;
    }
    location /donut_rhb/ {
	    proxy_pass http://donut_rhb:8000/;
      proxy_connect_timeout 300;
      proxy_send_timeout 300;
      proxy_read_timeout 300;
 
      client_max_body_size 10M;
    }
    location /customer_agent/ {
	    proxy_pass http://aiagent-frontend:3000/;
      proxy_connect_timeout 300;
      proxy_send_timeout 300;
      proxy_read_timeout 300;
 
      client_max_body_size 10M;
    }
    location /rm-agent/ {
      proxy_pass http://rm-agent:8000/;
      # Timeouts
      proxy_connect_timeout 300;
      proxy_send_timeout 300;
      proxy_read_timeout 300;
      # CRITICAL for file uploads
      client_max_body_size 100M;
      # Header passing
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Path /rm-agent;
    }
 
  }
}